# https://superuser.com/a/583502/225931
export PLATFORM=$(uname -s)

if [ "$PLATFORM" = 'Darwin' ] && [ -f /etc/profile ]; then
  PATH=
  source /etc/profile
fi

. ~/.bashrc


export ENABLE_MAVEN_LOCAL=true

# https://apple.stackexchange.com/questions/371997/suppressing-the-default-interactive-shell-is-now-zsh-message-in-macos-catalina
export BASH_SILENCE_DEPRECATION_WARNING=1

export GPG_TTY=$(tty)

# Created by `pipx` on 2025-07-03 04:55:16
export PATH="$PATH:/Users/user/.local/bin"
